Refactor and use global rather than STDOUT for function results to allow auto and engine logs on STDOUT

diff --git a/bin/nvh b/bin/nvh
--- a/bin/nvh
+++ b/bin/nvh
@@ -64,6 +64,10 @@ WGET_OPTIONS=( "-q" "-O-" )
 # Set by set_active_node
 g_active_node=
 
+# set by various lookups to allow mixed logging and return value from function, especially for engine and node
+g_target_node=
+
+
 # Set by find_cached_version
 g_cached_version=
 
@@ -175,14 +179,11 @@ function update_xz_settings_for_version() {
 }
 
 #
-# Synopsis: install_log action message
+# Synopsis: log action message
 #
 
-function install_log() {
+function log() {
   printf "  ${SGR_CYAN}%10s${SGR_RESET} : ${SGR_FAINT}%s${SGR_RESET}\n" "$1" "$2"
-}
-function trace_log() {
-  >&2 install_log "$1" "$2"
 }
 
 #
@@ -738,8 +739,8 @@ function activate() {
 
   local active_node="$(command -v node)"
   if [[ -e "${active_node}" && -e "${installed_node}" && "${active_node}" != "${installed_node}" ]]; then
-    install_log "installed" "$("${installed_node}" --version) to ${installed_node}"
-    install_log "active" "$("${active_node}" --version) at ${active_node}"
+    log "installed" "$("${installed_node}" --version) to ${installed_node}"
+    log "active" "$("${active_node}" --version) at ${active_node}"
   else
     local npm_version_str=""
     local installed_npm="${NVH_PREFIX}/bin/npm"
@@ -747,13 +748,13 @@ function activate() {
     if [[ -z "${NVH_PRESERVE_NPM}" && -e "${active_npm}" && -e "${installed_npm}" && "${active_npm}" = "${installed_npm}" ]]; then
       npm_version_str=" (with npm $(npm --version))"
     fi
-    install_log "installed" "$("${installed_node}" --version)${npm_version_str}"
+    log "installed" "$("${installed_node}" --version)${npm_version_str}"
 
     # Extra tips for changed location.
     if [[ -e "${active_node}" && -e "${original_node}" && "${active_node}" != "${original_node}" ]]; then
       printf '\nNote: the node command changed location and the old location may be remembered in your current shell.\n'
-      install_log old "${original_node}"
-      install_log new "${active_node}"
+      log old "${original_node}"
+      log new "${active_node}"
       # shellcheck disable=SC2016
       printf 'To reset the command location hash either start a new shell, or execute PATH="$PATH"\n'
     fi
@@ -767,7 +768,8 @@ function activate() {
 function install() {
   [[ -z "$1" ]] && abort "version required"
   local resolved_version
-  resolved_version="$(display_latest_resolved_version "$1")" || return 2
+  get_latest_resolved_version "$1" || return 2
+  resolved_version="${g_target_node}"
   [[ -n "${resolved_version}" ]] || abort "no version found for '$1'"
   update_mirror_settings_for_version "$1"
   update_xz_settings_for_version "${resolved_version}"
@@ -782,7 +784,7 @@ function install() {
   fi
 
   echo
-  install_log "installing" "${g_mirror_folder_name}/${resolved_version}"
+  log "installing" "${g_mirror_folder_name}/${resolved_version}"
 
   local url="$(tarball_url "${resolved_version}")"
   is_ok "${url}" || abort "download preflight failed for '$resolved_version' (${url})"
@@ -790,13 +792,13 @@ function install() {
   local tarflags="-zx"
   if [[ "${NVH_USE_XZ}" = "true" ]]; then local tarflags="-Jx"; fi
 
-  install_log "mkdir" "${dir}"
+  log "mkdir" "${dir}"
   mkdir -p "${dir}" || abort "sudo required (or change ownership, or define NVH_PREFIX)"
   touch "${dir}/nvh.lock"
 
   cd "${dir}" || abort "Failed to cd to directory"
 
-  install_log "fetch" "${url}"
+  log "fetch" "${url}"
   do_get "${url}" | tar "${tarflags}" --strip-components=1 --no-same-owner
   if [[ "${PIPESTATUS[0]}" -ne 0 ]]; then
     abort "failed to download archive for $resolved_version"
@@ -818,7 +820,8 @@ function remove_versions() {
   [[ -z "$1" ]] && abort "version(s) required"
   while [[ $# -ne 0 ]]; do
     local version
-    version="$(display_latest_resolved_version "$1")" || break
+    get_latest_resolved_version "$1" || break
+    version="${g_target_node}"
     if [[ -n "${version}" ]]; then
       update_mirror_settings_for_version "$1"
       local dir="${CACHE_DIR}/${g_mirror_folder_name}/${version}"
@@ -870,7 +873,8 @@ function clear_cache() {
 function find_cached_version() {
   [[ -z "$1" ]] && abort "version required"
   local version
-  version="$(display_latest_resolved_version "$1")" || exit 1
+  get_latest_resolved_version "$1" || exit 1
+  version="${g_target_node}"
   [[ -n "${version}" ]] || abort "no version found for '$1'"
 
   update_mirror_settings_for_version "$1"
@@ -911,34 +915,38 @@ function exec_with_version() {
 }
 
 #
-# Synopsis: display_file_node_version filename
+# Synopsis: get_file_node_version filename
+# Sets g_target_node
 #
 
-function display_file_node_version() {
+function get_file_node_version() {
   local filepath="$1"
-  trace_log "found" "${filepath}"
+  g_target_node=
+  log "found" "${filepath}"
   # read returns a non-zero status but does still work if there is no line ending
   local version
   <"${filepath}" read -r version
   # trim possible trailing \d from a Windows created file
   version="${version%%[[:space:]]}"
-  trace_log "read" "${version}"
-  echo "${version}"
+  log "read" "${version}"
+  g_target_node="${version}"
 }
 
 #
-# Synopsis: display_package_engine_version
+# Synopsis: get_package_engine_version
+# Sets g_target_node
 #
 
-function display_package_engine_version() {
+function get_package_engine_version() {
   local filepath="$1"
-  trace_log "found" "${filepath}"
+  g_target_node=
+  log "found" "${filepath}"
   command -v node &> /dev/null || abort "an active version of node is required to read 'engines' from package.json"
   local range
   range="$(node -e "package = require('${filepath}'); if (package && package.engines && package.engines.node) console.log(package.engines.node)")"
-  trace_log "read" "${range}"
+  log "read" "${range}"
   if [[ -z "${range}" || "*" == "${range}" ]]; then
-    echo "current"
+    g_target_node="current"
     return
   fi
 
@@ -954,26 +962,28 @@ function display_package_engine_version() {
     esac
   else
     command -v npx &> /dev/null || abort "an active version of npx is required to use complex 'engine' ranges from package.json"
-    trace_log "resolving" "${range}"
+    log "resolving" "${range}"
     local version_per_line="$(nvh lsr --all)"
     local versions_one_line=$(echo "${version_per_line}" | tr '\n' ' ')
     # Using semver@7 so works with older versions of node.
     # shellcheck disable=SC2086
     version=$(npm_config_yes=true npx --quiet semver@7 -r "${range}" ${versions_one_line} | tail -n 1)
   fi
-  echo "${version}"
+  g_target_node="${version}"
 }
 
 #
-# Synopsis: display_nvmrc_version
+# Synopsis: get_nvmrc_version
+# Sets g_target_node
 #
 
-function display_nvmrc_version() {
+function get_nvmrc_version() {
   local filepath="$1"
-  trace_log "found" "${filepath}"
+  g_target_node=
+  log "found" "${filepath}"
   local version
   <"${filepath}" read -r version
-  trace_log "read" "${version}"
+  log "read" "${version}"
   # Translate from nvm aliases
   case "${version}" in
     lts/\*) version="lts" ;;
@@ -981,25 +991,27 @@ function display_nvmrc_version() {
     node) version="current" ;;
     *) ;;
   esac
-  echo "${version}"
+  g_target_node="${version}"
 }
 
 #
-# Synopsis: display_auto_version
+# Synopsis: get_auto_version
+# Sets g_target_node
 #
 
-function display_auto_version() {
+function get_auto_version() {
+  g_target_node=
   local parent
   parent="${PWD}"
   while [[ -n "${parent}" ]]; do
     if [[ -e "${parent}/.nvh-node-version" ]]; then
-      display_file_node_version "${parent}/.nvh-node-version"
+      get_file_node_version "${parent}/.nvh-node-version"
     elif [[ -e "${parent}/.node-version" ]]; then
-      display_file_node_version "${parent}/.node-version"
+      get_file_node_version "${parent}/.node-version"
     elif [[ -e "${parent}/.nvmrc" ]]; then
-      display_nvmrc_version "${parent}/.nvmrc"
+      get_nvmrc_version "${parent}/.nvmrc"
     elif [[ -e "${parent}/package.json" ]]; then
-      display_package_engine_version "${parent}/package.json"
+      get_package_engine_version "${parent}/package.json"
     else
       parent=${parent%/*}
       continue
@@ -1010,22 +1022,25 @@ function display_auto_version() {
 }
 
 #
-# Synopsis: display_latest_resolved_version version
+# Synopsis: get_latest_resolved_version version
+# Sets g_target_node
 #
 
-function display_latest_resolved_version() {
+function get_latest_resolved_version() {
   local version=${1}
+  g_target_node=
   if [[ "${version}" = "auto" ]]; then
-    version="$(display_auto_version)" || return 2
+    get_auto_version || return 2
+    version="${g_target_node}"
   fi
   simple_version=${version#node/} # Only place supporting node/ [sic]
   if is_exact_numeric_version "${simple_version}"; then
     # Just numbers, already resolved, no need to lookup first.
     simple_version="v${simple_version#v}"
-    echo "${simple_version}"
+    g_target_node="${simple_version}"
   else
     # Complicated recognising exact version, KISS and lookup.
-    NVH_MAX_REMOTE_MATCHES=1 display_remote_versions "${version}"
+    g_target_node="$(NVH_MAX_REMOTE_MATCHES=1 display_remote_versions "${version}")"
   fi
 }
 
@@ -1404,7 +1419,7 @@ function main() {
   readonly CURL_OPTIONS
   readonly WGET_OPTIONS
   readonly GET_OPTIONS_SHOW_PROGRESS
-  # Note: NVH_MAX_REMOTE_MATCHES not readonly, used as env in display_latest_resolved_version
+  # Note: NVH_MAX_REMOTE_MATCHES not readonly, used as env in get_latest_resolved_version
 
   if [[ -z "${NVH_USE_XZ+defined}" ]]; then
     NVH_USE_XZ="true" # Default to using xz
@@ -1432,7 +1447,7 @@ function main() {
       run) shift; run_with_version "$@" ;;
       uninstall) uninstall_installed ;;
       which) shift; display_bin_path_for_version "$1" ;;
-      NVH_TEST_DISPLAY_LATEST_RESOLVED_VERSION) shift; display_latest_resolved_version "$1"; exit ;;
+      NVH_TEST_DISPLAY_LATEST_RESOLVED_VERSION) shift; get_latest_resolved_version "$1" > /dev/null; echo "${g_target_node}"; exit ;;
       *) abort "unrecognised command '$1' (perhaps you want 'nvh install $1'?)" ;;
     esac
   fi
